### ISSUE TITLE
secure chat and visualize_key issues in 1.3.3

### ISSUE THREAD

**Issue by danielberlin** [vysheng/tgl#104]
I send out telegram messages with `telegram-cli -W -e 'msg !_<userid> text` (1.3.3, CentOS RPM) to secure chats which are read an the latest Android telegram app.

1. Only recently since a few days it repeatedly occured that the secure chat was shown as "terminated". I'm not sure if this is an issue in telegram-cli or Telegram (Android) or possibly even in MPROTO?

2. Anyway, the command `visualize_key` seems to be broken. The first time after initiating a new secret chat it works, but after closing the telegram-cli session and restarting telegram-cli, `visualize_key` only shows an entirely grey box instead of the key. The secure chat itself however works so I assume this is a telegram-cli problem and could also be related to the first obseration.

**Comment by BenWiederhake** [comment]
Thanks for the report, but I guess this is more closely related to [tg-cli](https://github.com/vysheng/tg).

The second point may have already been fixed in commit 4fff59712e3c7719dcc21d3c35610638304bd263 , which is included in both the branches `master` and `test`, so simply updating might fix this.

**Comment by danielberlin** [comment]
Thanks for the quick info. I'll post again to [tg-cli](https://github.com/vysheng/tg).
