### ISSUE TITLE
compile error: queries.c: In function ‘_tgl_do_send_photo’

### ISSUE THREAD

**Issue by Randomneo** [vysheng/tgl#137]
Error:
```
queries.c:2091:10: error: cast between incompatible function types from ‘void (*)(struct tgl_state *, void *, int,  struct tgl_message *)’ to ‘void (*)(struct tgl_state *, void *, int)’ [-Werror=cast-function-type]
         
((void (*)(struct tgl_state *, void *, int))callback) (TLS, callback_extra, 0);

queries.c:2108:10: error: cast between incompatible function types from ‘void (*)(struct tgl_state *, void *, int,  struct tgl_message *)’ to ‘void (*)(struct tgl_state *, void *, int)’ [-Werror=cast-function-type]
        
 ((void (*)(struct tgl_state *, void *, int))callback) (TLS, callback_extra, 0);
          
queries.c:2141:10: error: cast between incompatible function types from ‘void (*)(struct tgl_state *, void *, int,  struct tgl_message *)’ to ‘void (*)(struct tgl_state *, void *, int)’ [-Werror=cast-function-type]
         
((void (*)(struct tgl_state *, void *, int))callback) (TLS, callback_extra, 0);`
```
Gcc version:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.1.0 (GCC)
```

**Comment by BenWiederhake** [comment]
That seems to be mainly your fault for enabling `-Werror` without knowing what it does.  Disable -Werror.

See this blog post why blanket-enabling `-Werror` and just stopping on *any* kind of warning whatsoever leads to the fragile behavior you're observing: http://blog.schmorp.de/2016-02-27-tidbits-for-the-love-of-god-dont-use-werror.html

Warnings are good!  And in this case, the compiler complains about ugly C code.  But it it safe and reasonable C code.  So the warning is just that here: A warning.  A recommendation "Hey, please don't do this, or know what you're doing."

To those who read the tgp-dev chat: It's the same response text because it's literally the same issue.

**Comment by Randomneo** [comment]
Thank you.
I dont know how -werror get in auto generated makefile.

**Comment by WriterOfAlicrow** [comment]
Makefile.in contains the following line:

> COMPILE_FLAGS=${CFLAGS} ${CPFLAGS} ${CPPFLAGS} ${DEFS} -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC

I believe that would set the -Werror flag in the generated Makefile.

**Comment by BenWiederhake** [comment]
Tell that vysheng.  Or use a [different fork](https://github.com/majn/tgl).  I'm not going to say ours is better, it just has different disadvantages.
